# Generated by Django 5.0 on 2024-10-20 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('Business', 'Business'), ('Education', 'Education'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=15)),
                ('deposit_amt', models.IntegerField(verbose_name='Amt in Ksh')),
                ('duration_in_months', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1')),
                ('deposited_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Joint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_first_name', models.CharField(max_length=255, verbose_name='partner first name')),
                ('partner_last_name', models.CharField(max_length=255, verbose_name='partner last name')),
                ('joint_amt', models.IntegerField(blank=True, default=False, verbose_name='Joint depo in Ksh')),
                ('purpose', models.CharField(choices=[('Business', 'Business'), ('Education', 'Education'), ('Health', 'Health'), ('Other', 'Other')], default='Other', max_length=15)),
                ('duration_in_months', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='1')),
                ('deposited_on', models.DateTimeField(auto_now_add=True)),
                ('individual', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='sacco.individual')),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
